//! Contains the core data structures and models for the application.

use async_graphql::{InputObject, SimpleObject};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

/// Represents a single AI code audit record in the database.
#[derive(Debug, Serialize, Deserialize, FromRow, SimpleObject)]
#[graphql(name = "AiAudit")]
pub struct AiAudit {
    /// The unique identifier for the audit.
    pub id: Uuid,
    /// The prompt that was given to the AI.
    pub prompt: String,
    /// The code that was generated by the AI.
    #[graphql(name = "generatedCode")]
    pub generated_code: String,
    /// A boolean indicating whether the generated code compiled successfully.
    #[graphql(name = "isValid")]
    pub is_valid: bool,
    /// The compilation error message, if any.
    #[graphql(name = "compilationError")]
    pub compilation_error: Option<String>,
    /// The timestamp when the audit was created.
    #[graphql(name = "createdAt")]
    pub created_at: DateTime<Utc>,
}

/// Represents the incoming request payload for creating a new audit.
#[derive(Debug, Deserialize, InputObject)]
pub struct CreateAuditRequest {
    /// The prompt that was given to the AI.
    pub prompt: String,
    /// The code that was generated by the AI.
    pub generated_code: String,
}

/// Represents the statistics of all AI code audits.
#[derive(Debug, Serialize, Deserialize, SimpleObject)]
#[graphql(name = "AuditStats")]
pub struct AuditStats {
    /// The total number of audits performed.
    #[graphql(name = "totalAudits")]
    pub total_audits: i64,
    /// The number of audits where the code was valid.
    #[graphql(name = "validAudits")]
    pub valid_audits: i64,
    /// The number of audits where the code was invalid.
    #[graphql(name = "invalidAudits")]
    pub invalid_audits: i64,
    /// The ratio of valid audits to total audits (0.0 to 1.0).
    #[graphql(name = "validationRate")]
    pub validation_rate: f64,
    /// A list of the most common compilation errors.
    #[graphql(name = "commonErrors")]
    pub common_errors: Vec<CommonError>,
}

/// Represents a common compilation error and its frequency.
#[derive(Debug, Serialize, Deserialize, SimpleObject, FromRow)]
#[graphql(name = "CommonError")]
pub struct CommonError {
    /// The compilation error message.
    #[graphql(name = "errorMessage")]
    pub error_message: String,
    /// The number of times this error has occurred.
    pub frequency: i64,
}
